version: '3.4'

x-app: &app
  env_file: .env
  depends_on:
    - postgres

services:
  app:
    <<: *app
    ports:
      - '80:8080'
    environment:
      - DATABASE_HOST=postgres

  postgres:
    image: postgres:10.1
    ports:
      - '19999:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
